# Generated by Django 2.2.4 on 2019-09-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='internShipState',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='studentFinalReport',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='studentObjectionDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='studentObjectionText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='supervisorReportUploadUrl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
