# Generated by Django 2.2.4 on 2019-09-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_auto_20190914_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='opinion',
        ),
        migrations.AddField(
            model_name='opinion',
            name='opinion',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='term',
            field=models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester'), ('3', 'Summer')], max_length=15),
        ),
    ]
