# Generated by Django 2.2.4 on 2019-09-28 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_auto_20190925_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshiphead',
            name='phone',
        ),
    ]
