# Generated by Django 2.2.4 on 2019-09-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_auto_20190920_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='reqhash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
