# Generated by Django 2.2.4 on 2019-09-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_remove_internshiphead_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='choosing',
            name='choice',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
